services:
  zitadel:
    restart: unless-stopped
    image: ghcr.io/zitadel/zitadel:v4.6.6
    command: start-from-init --masterkeyFile /secrets/master.key --tlsMode external
    environment:
      ZITADEL_EXTERNALDOMAIN: sso.rezoleo.fr
      ZITADEL_EXTERNALPORT: 443
      ZITADEL_EXTERNALSECURE: false
      ZITADEL_TLS_ENABLED: false
      # Database
      ZITADEL_DATABASE_POSTGRES_HOST: host.docker.internal
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      # Admin Account
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: admin
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_FIRSTNAME: Admin
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_LASTNAME: Rézoléo
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: ${ADMIN_ACCOUNT_PASSWORD}
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: false
      # Login UI
      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED: false

    healthcheck:
      test:
      - CMD
      - /app/zitadel
      - ready
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - ./master.key:/secrets/master.key:ro
    ports:
      - 8080:8080
    networks:
      - zitadel
    extra_hosts:
      - "host.docker.internal:host-gateway"

  registration:
    build:
      context: ./registration-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      ZITADEL_BASE_URL: https://sso.rezoleo.fr
      ZITADEL_ORGANIZATION_ID: 333641516377505795
      ZITADEL_PAT: ${ZITADEL_REZOLEO_PAT}
    ports:
      - "8000:8000"
    networks:
      - zitadel
    depends_on:
      - zitadel

  action-target:
    build:
      context: ./action-target
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      ZITADEL_CONSOLE_URL: https://sso.rezoleo.fr/ui/console
    ports:
      - "8001:8001"
    networks:
      - zitadel
    depends_on:
      - zitadel

networks:
  zitadel:
